networks:
  caddy:
services:
  caddy:
    build: ./
    ports:
      - 80:80
      - 443:443
    environment:
      - ACME_KEY_ID=test
      - ACME_MAC_ID=test
      - JWT_SHARED_KEY=test
      - OAUTH_AUTH_URL=http://localhost/auth/oauth2/github
      - OAUTH_CLIENT_ID=test
      - OAUTH_CLIENT_SECRET=test
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  hello:
    image: ghcr.io/icco/hello:main
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - caddy
    labels:
      caddy.reverse_proxy: '{{upstreams 8080}}'
      caddy.log:
