networks:
  caddy:
services:
  caddy:
    build: ./
    ports:
      - 8080:80
      - 8081:443
    environment:
      - ACME_KEY_ID=test
      - ACME_MAC_ID=test
      - JWT_SHARED_KEY=test
      - OAUTH_AUTH_URL=http://localhost/auth/oauth2/github
      - OAUTH_CLIENT_ID=test
      - OAUTH_CLIENT_SECRET=test
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
